In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# create a synthetic classification dataset using sklearn

X,y= make_classification(
    n_samples=10,     #no. of samples
    n_features=2,     #no. of features
    n_redundant=0,    #no. of redundant features
    n_classes=2,      #no. of classes
    random_state=2,
    n_informative=2  # no. of informative features
)

In [3]:
X

array([[ 1.19233761,  1.68984837],
       [ 2.10468347,  0.08822   ],
       [ 1.04115518, -1.91602762],
       [ 0.28432141, -0.11450983],
       [-0.67458929, -0.89813178],
       [ 0.97869965, -0.57896825],
       [-1.30136943,  0.79786149],
       [ 1.17062352,  0.99746752],
       [-0.12196157, -2.58441629],
       [-0.98692549,  0.68339532]])

In [4]:
y

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [5]:
X.shape

(10, 2)

In [6]:
y.shape

(10,)

In [8]:
X=torch.tensor(X, dtype=torch.float32)
y=torch.tensor(y, dtype=torch.long)

C:\Users\HP\AppData\Local\Temp\ipykernel_33708\2836881727.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X=torch.tensor(X, dtype=torch.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_33708\2836881727.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y=torch.tensor(y, dtype=torch.long)


In [10]:
X

tensor([[ 1.1923,  1.6898],
        [ 2.1047,  0.0882],
        [ 1.0412, -1.9160],
        [ 0.2843, -0.1145],
        [-0.6746, -0.8981],
        [ 0.9787, -0.5790],
        [-1.3014,  0.7979],
        [ 1.1706,  0.9975],
        [-0.1220, -2.5844],
        [-0.9869,  0.6834]])

In [11]:
y

tensor([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [12]:
from torch.utils.data import Dataset, DataLoader

In [17]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features= features
        self.labels=labels
        
    def __len__ (self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [18]:
dataset=CustomDataset(X,y)

In [19]:
len(dataset)

10

In [20]:
dataset[2]

(tensor([ 1.0412, -1.9160]), tensor(0))

In [22]:
dataloader=DataLoader(dataset, batch_size=2, shuffle=True )

In [25]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[-0.1220, -2.5844],
        [-0.9869,  0.6834]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.1923,  1.6898],
        [-0.6746, -0.8981]])
tensor([1, 0])
--------------------------------------------------
tensor([[2.1047, 0.0882],
        [1.1706, 0.9975]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.3014,  0.7979],
        [ 0.9787, -0.5790]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 0.2843, -0.1145],
        [ 1.0412, -1.9160]])
tensor([0, 0])
--------------------------------------------------
